# Generated by Django 4.2 on 2023-04-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_course_course_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
