# Generated by Django 4.2 on 2023-04-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_assignmentsubmission_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submitted_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
